name = "digikala-mcp"
main = "src/worker.js"
compatibility_date = "2026-09-19"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "digikala-price-history"
database_id = "7b32478e-f9a7-489f-bfd0-53ad8c50461e"

